import type { Season, ShowInfo } from "../model/types";

export const SHOW_INFO: ShowInfo = {
  titleKo: "나는 SOLO",
  titleEn: "I AM SOLO",
  officialVod: "https://programs.sbs.co.kr/plus/iamsolo/vods/69610",
};

/**
 * 전 기수 데이터.
 * - 새 기수 추가 시 배열 맨 앞에 추가(최신순 정렬 유지).
 * - instagram 필드: 실제 username 확인 후 입력 (@제외).
 */
export const SEASONS_DATA: Season[] = [
  {
    seasonNo: 30,
    label: "30기 (에겐남 & 테토녀)",
    episodes: [
      { ep: 238, airDate: "2026-02-04" },
      { ep: 239, airDate: "2026-02-11" },
    ],
    participants: [
      {
        seasonNo: 30,
        gender: "M",
        handle: "영수",
        photo: { src: null, alt: "나는 SOLO 30기 영수" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "패션 브랜드 회사 신규 브랜드 기획",
          region: "서울 중구 거주",
          traits: ["에겐남", "커리어 이동 경험 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 남자 출연자 직업 공개(영수/영호/영식/영철/광수)",
            url: "https://www.osen.co.kr/article/G1112739784",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "M",
        handle: "영호",
        photo: { src: null, alt: "나는 SOLO 30기 영호" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "에너지 전력 공기업 배관 설계(전역 후 엔지니어)",
          region: null,
          traits: ["해군사관학교/장교 경력 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 남자 출연자 직업 공개(영호 소개 포함)",
            url: "https://www.osen.co.kr/article/G1112739784",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "M",
        handle: "영식",
        photo: { src: null, alt: "나는 SOLO 30기 영식" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "부동산 전문 변호사 / 로펌 대표",
          region: null,
          traits: ["전문직", "감정기복 적다고 어필"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 남자 출연자 직업 공개(영식 소개 포함)",
            url: "https://www.osen.co.kr/article/G1112739784",
            confidence: "high",
          },
          {
            title: "tvdaily(다음): 30기 자기소개(영식/영자 관련 언급)",
            url: "https://v.daum.net/v/20260205000742464",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "M",
        handle: "영철",
        photo: { src: null, alt: "나는 SOLO 30기 영철" },
        instagram: null,
        profile: {
          birthYear: 1991,
          ageKorean: null,
          job: "태양광 발전 사업(대구·경북, 가업 이어받는 중)",
          region: "대구·경북",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 남자 출연자 직업 공개(영철 소개 포함)",
            url: "https://www.osen.co.kr/article/G1112739784",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "M",
        handle: "광수",
        photo: { src: null, alt: "나는 SOLO 30기 광수" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "삼성 반도체 엔지니어(전자전기 학·석)",
          region: null,
          traits: ["과학고 졸업 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 남자 출연자 직업 공개(광수 소개 포함)",
            url: "https://www.osen.co.kr/article/G1112739784",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "M",
        handle: "상철",
        photo: { src: null, alt: "나는 SOLO 30기 상철" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: null,
          region: null,
          traits: [],
          notableQuotes: [],
          issues: [
            "신뢰도 높은 단일 기사에서 직업/나이를 아직 확보 못함(추가 리서치 필요)",
          ],
        },
        sources: [
          {
            title: "SBS 다시보기(회차/방영일 확인)",
            url: "https://programs.sbs.co.kr/plus/iamsolo/vods/69610",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "영숙",
        photo: { src: null, alt: "나는 SOLO 30기 영숙" },
        instagram: null,
        profile: {
          birthYear: 1991,
          ageKorean: null,
          job: "외국계 제약회사 마케팅(약학대학 졸업, 약사)",
          region: "서울 동작구",
          traits: ["자기관리(영단어 암기 루틴 언급)"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(영숙/정숙/순자/옥순/영자/현숙)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "정숙",
        photo: { src: null, alt: "나는 SOLO 30기 정숙" },
        instagram: null,
        profile: {
          birthYear: 1993,
          ageKorean: null,
          job: "경기도 소재 경찰청 소속 경찰 공무원",
          region: "의정부 거주(업무로 거주 언급)",
          traits: ["솔로나라 최초 직업이라고 소개", "체력 걱정 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(정숙 경찰 공무원 언급)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
          {
            title: "OSEN: 30기 테토녀 등장(정숙 경찰공무원 언급)",
            url: "https://www.osen.co.kr/article/G1112736029",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "순자",
        photo: { src: null, alt: "나는 SOLO 30기 순자" },
        instagram: null,
        profile: {
          birthYear: 1995,
          ageKorean: null,
          job: "계열사 헬스 브랜드 상품 기획/개발(PM)",
          region: "서울 관악구(울산 출생 언급)",
          traits: ["복싱 생활체육 대회 출전 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(순자 직무/복싱 언급)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
          {
            title: "OSEN: 30기 테토녀 등장(복싱 아마추어 언급)",
            url: "https://www.osen.co.kr/article/G1112736029",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "옥순",
        photo: { src: null, alt: "나는 SOLO 30기 옥순" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: "필라테스 센터 2곳 운영(무용 전공)",
          region: null,
          traits: ["선화예중·예고, 이화여대 무용과 졸업 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(옥순 무용/필라테스 운영)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "영자",
        photo: { src: null, alt: "나는 SOLO 30기 영자" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: "건설 현장 근무(H건설 현장 근무직 언급)",
          region: null,
          traits: [
            "이동 잦아 장거리/주말부부 이슈",
            "한식기능사·요리/재봉/낚시/캠핑 언급",
            "서울 자가 언급",
          ],
          notableQuotes: ['"주말 부부 어떠냐" 질문 언급'],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(영자 현장근무/서울 자가 등)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
          {
            title: "tvdaily(다음): 30기 자기소개(영자 직업 맥락 언급)",
            url: "https://v.daum.net/v/20260205000742464",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 30,
        gender: "F",
        handle: "현숙",
        photo: { src: null, alt: "나는 SOLO 30기 현숙" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: "국제 회계법인 텍스 매니저(미국·캐나다 회계사 자격)",
          region: "캐나다 밴쿠버 고향(자가 언급)",
          traits: ["미국·캐나다 회계사 자격증 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN: 30기 여성 출연자 스펙(현숙 회계사/밴쿠버 자가)",
            url: "https://www5.osen.co.kr/article/G1112739811",
            confidence: "high",
          },
        ],
      },
    ],
  },
  {
    seasonNo: 29,
    label: "29기 (연상연하 특집)",
    episodes: [
      { ep: 228, airDate: "2025-11-19" },
      { ep: 229, airDate: "2025-11-26" },
    ],
    participants: [
      {
        seasonNo: 29,
        gender: "F",
        handle: "영숙",
        photo: { src: null, alt: "나는 SOLO 29기 영숙" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "서울 소재 대학교 연구 전담 교수",
          region: "제주 출신(언급)",
          traits: ["수영 선수 경험 언급", "장거리/나이 열려 있다고 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(영숙/정숙/순자/영자/옥순/현숙)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "F",
        handle: "정숙",
        photo: { src: null, alt: "나는 SOLO 29기 정숙" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "대구 영어 학원 운영",
          region: "대구",
          traits: ['"정말 사랑한다면 길을 만들고 싶다" 취지 언급'],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(정숙 영어학원 운영)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "F",
        handle: "순자",
        photo: { src: null, alt: "나는 SOLO 29기 순자" },
        instagram: null,
        profile: {
          birthYear: 1990,
          ageKorean: null,
          job: "부친 건설회사 분양관리팀 근무(서울·광주 오가며)",
          region: "서울·광주",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(순자 분양관리팀)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "F",
        handle: "영자",
        photo: { src: null, alt: "나는 SOLO 29기 영자" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "대치동 수학 학원 운영",
          region: "서울 대치동",
          traits: ['"모은 건 없지만 잘 번다" 취지 언급'],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(영자 수학학원 운영)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "F",
        handle: "옥순",
        photo: { src: null, alt: "나는 SOLO 29기 옥순" },
        instagram: null,
        profile: {
          birthYear: 1989,
          ageKorean: null,
          job: "병원 간호사(13년차, 간호사 국가고시 전국 수석 언급)",
          region: "서울(기사 기준)",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(옥순 간호사/국시 수석 언급)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "F",
        handle: "현숙",
        photo: { src: null, alt: "나는 SOLO 29기 현숙" },
        instagram: null,
        profile: {
          birthYear: 1990,
          ageKorean: null,
          job: "약사(3년차)",
          region: null,
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "MK: 29기 연상녀 자기소개(현숙 약사 3년차)",
            url: "https://www.mk.co.kr/news/broadcasting-service/11483777",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "영수",
        photo: { src: null, alt: "나는 SOLO 29기 영수" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["3개국어 구사", "소개팅 100번 이상(언급)"],
          notableQuotes: ['"미치도록 예쁘다"(첫인상 선택 멘트로 언급)'],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필/멘트)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "영호",
        photo: { src: null, alt: "나는 SOLO 29기 영호" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["200평 오리 식당 막내아들(언급)", "연상 선호(언급)"],
          notableQuotes: [],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "영식",
        photo: { src: null, alt: "나는 SOLO 29기 영식" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["K대 출신(언급)", "나이 제한 없음(언급)"],
          notableQuotes: [],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "영철",
        photo: { src: null, alt: "나는 SOLO 29기 영철" },
        instagram: null,
        profile: {
          birthYear: null,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["유도 선수 출신(언급)", "아이 5명 원함(언급)"],
          notableQuotes: [],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "광수",
        photo: { src: null, alt: "나는 SOLO 29기 광수" },
        instagram: null,
        profile: {
          birthYear: 1994,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["8세 연상과 연애 경험(언급)"],
          notableQuotes: [],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 29,
        gender: "M",
        handle: "상철",
        photo: { src: null, alt: "나는 SOLO 29기 상철" },
        instagram: null,
        profile: {
          birthYear: 1997,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["8세 연상까지 가능(언급)", "황금색 래핑카(언급)"],
          notableQuotes: [],
          issues: ["직업/지역은 기사에서 확정적으로 못 찾음"],
        },
        sources: [
          {
            title: "bnt(다음): 나는솔로 29기 프로필(요약 프로필)",
            url: "https://v.daum.net/v/20251127074546302",
            confidence: "medium",
          },
        ],
      },
    ],
  },
  {
    seasonNo: 28,
    label: "28기 (돌싱 특집)",
    episodes: [{ ep: 217, airDate: "2025-09-03" }],
    participants: [
      {
        seasonNo: 28,
        gender: "M",
        handle: "영수",
        photo: { src: null, alt: "나는 SOLO 28기 영수" },
        instagram: null,
        profile: {
          birthYear: 1984,
          ageKorean: null,
          job: "식품 관련 스타트업 CEO(국무총리 표창 경력 언급)",
          region: null,
          traits: [
            "자녀 없는 돌싱(방송 자기소개 기준)",
            "재혼 시 상대 자녀 양육 의지 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(영수 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "영호",
        photo: { src: null, alt: "나는 SOLO 28기 영호" },
        instagram: null,
        profile: {
          birthYear: 1989,
          ageKorean: null,
          job: "잠수·인명구조 장비 납품 사업",
          region: null,
          traits: [
            "3년 사실혼 후 이혼 언급",
            "자녀 있는 상대도 가능하다고 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(영호 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "영식",
        photo: { src: null, alt: "나는 SOLO 28기 영식" },
        instagram: null,
        profile: {
          birthYear: 1980,
          ageKorean: null,
          job: "도시계획 엔지니어",
          region: "광주",
          traits: ["18세 딸 양육 언급", "딸 권유로 출연 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(영식 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "영철",
        photo: { src: null, alt: "나는 SOLO 28기 영철" },
        instagram: null,
        profile: {
          birthYear: 1983,
          ageKorean: null,
          job: "연구원",
          region: "대전 근무(자기소개 기준)",
          traits: [
            "충남 서산 출신 언급",
            "한양대 공학 박사 언급",
            "자가 4채 보유 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(영철 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
          {
            title: "머니투데이(다음): 28기 영철 공학박사/자가 4채",
            url: "https://v.daum.net/v/20250904024547047",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "광수",
        photo: { src: null, alt: "나는 SOLO 28기 광수" },
        instagram: null,
        profile: {
          birthYear: 1981,
          ageKorean: null,
          job: "음반 제작 총괄 이사",
          region: null,
          traits: ["딸을 생후 6개월부터 양육, 현재 고3이라고 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(광수 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "상철",
        photo: { src: null, alt: "나는 SOLO 28기 상철" },
        instagram: null,
        profile: {
          birthYear: 1983,
          ageKorean: null,
          job: "대학병원 교직원",
          region: "충북 청주",
          traits: ["정년보장·사학연금 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(상철 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "M",
        handle: "경수",
        photo: { src: null, alt: "나는 SOLO 28기 경수" },
        instagram: null,
        profile: {
          birthYear: 1978,
          ageKorean: null,
          job: "스포츠 영상 스타트업·축구 교실 운영",
          region: null,
          traits: ["한국 1호 유럽 진출 골키퍼 출신 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "OSEN(다음): 28기 솔로남 스펙(경수 자기소개)",
            url: "https://v.daum.net/v/20250911073049863",
            confidence: "high",
          },
          {
            title: "텐아시아(다음): 28기 경수 1978년생 언급",
            url: "https://v.daum.net/v/20251027210339517",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "영숙",
        photo: { src: null, alt: "나는 SOLO 28기 영숙" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "간호사(나이트 근무 언급)",
          region: null,
          traits: ["두 자녀 양육 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(영숙 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "정숙",
        photo: { src: null, alt: "나는 SOLO 28기 정숙" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "회계사",
          region: null,
          traits: ["이상형으로 책임감 강한 남자 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(정숙 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "순자",
        photo: { src: null, alt: "나는 SOLO 28기 순자" },
        instagram: null,
        profile: {
          birthYear: 1987,
          ageKorean: null,
          job: "수학학원 강사",
          region: null,
          traits: ["6세 아들 양육 언급", "소송 이혼 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(순자 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "영자",
        photo: { src: null, alt: "나는 SOLO 28기 영자" },
        instagram: null,
        profile: {
          birthYear: 1983,
          ageKorean: null,
          job: "피아노 학원 원장",
          region: null,
          traits: ["온라인 쇼핑몰·베이킹숍 운영(쓰리잡) 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(영자 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "옥순",
        photo: { src: null, alt: "나는 SOLO 28기 옥순" },
        instagram: null,
        profile: {
          birthYear: 1991,
          ageKorean: null,
          job: "학원 팀장급 강사",
          region: null,
          traits: ["7세 딸 양육 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(옥순 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "현숙",
        photo: { src: null, alt: "나는 SOLO 28기 현숙" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "플로리스트",
          region: null,
          traits: ["세 자녀 양육 언급", "부업으로 부동산 경매 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(현숙 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 28,
        gender: "F",
        handle: "정희",
        photo: { src: null, alt: "나는 SOLO 28기 정희" },
        instagram: null,
        profile: {
          birthYear: 1985,
          ageKorean: null,
          job: "치과의사",
          region: "서울",
          traits: ["8세 딸 양육 언급", "서울 개원 언급"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt(다음): 28기 돌싱녀 스펙(정희 자기소개)",
            url: "https://v.daum.net/v/20250918073646728",
            confidence: "high",
          },
          {
            title: "텐아시아(다음): 28기 정희 직업/거주 추가 확인",
            url: "https://v.daum.net/v/20250918074038779",
            confidence: "medium",
          },
        ],
      },
    ],
  },
  {
    seasonNo: 27,
    label: "27기 (F6+6옥순)",
    episodes: [
      { ep: 215, airDate: "2025-07-02" },
      { ep: 216, airDate: "2025-07-09" },
    ],
    participants: [
      {
        seasonNo: 27,
        gender: "M",
        handle: "영수",
        photo: { src: null, alt: "나는 SOLO 27기 영수" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "식품 인허가 전문 행정사(배우 출신, 영상 제작업 이후 전업)",
          region: null,
          traits: [
            "결혼 지향적, 거주지·결혼관 중시",
            "차로 2시간 이내 거리 선호 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 솔로남 스펙(영수 자기소개)'",
            url: "https://v.daum.net/v/20250709094144032",
            confidence: "high",
          },
          {
            title: "블로그: 나는solo 27기 남자 영수 행정사·86년생",
            url: "https://blog.naver.com/chummilmil99/223928528212",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "M",
        handle: "영호",
        photo: { src: null, alt: "나는 SOLO 27기 영호" },
        instagram: null,
        profile: {
          birthYear: 1987,
          ageKorean: null,
          job: "학원 강사(연세대 기계공학과 출신)",
          region: null,
          traits: [
            "실없는 말 잘 받아주는 상대를 이상형으로 언급",
            "올해 말 또는 내년 결혼 희망 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개' (영호 소개)",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
          {
            title: "블로그: 나는solo 27기 남자 영호 87년생 학원강사",
            url: "https://blog.naver.com/chummilmil99/223928528212",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "M",
        handle: "영식",
        photo: { src: null, alt: "나는 SOLO 27기 영식" },
        instagram: null,
        profile: {
          birthYear: 1990,
          ageKorean: null,
          job: "해양수산부 소속 토목직 7급 공무원",
          region: null,
          traits: [
            "2~3년 간격 인사 이동으로 전국 이동 위주 업무",
            "장거리 연애·주말 부부 가능성을 열어 둔 태도 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개' (영식 소개)",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "M",
        handle: "영철",
        photo: { src: null, alt: "나는 SOLO 27기 영철" },
        instagram: null,
        profile: {
          birthYear: 1990,
          ageKorean: null,
          job: "IT 컨설턴트·프로젝트 매니저(부산 클라우드IT 회사, MS 파트너사)",
          region: "부산 거주(해운대 언급)",
          traits: [
            "티존이 예쁜 상대 선호 언급",
            "출산에 무리 없는 나이의 상대 선호 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개' (영철 소개)",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "M",
        handle: "광수",
        photo: { src: null, alt: "나는 SOLO 27기 광수" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "피부미용병원 일반의(의사)",
          region: null,
          traits: [
            "독실한 기독교인",
            "헬스·킥복싱 등 운동·피트니스 취미",
            "장기자랑에서 성시경 <내게 오는 길>을 부르며 반전 매력 어필",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개' (광수 소개)",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "M",
        handle: "상철",
        photo: { src: null, alt: "나는 SOLO 27기 상철" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "한국전력공사 직원",
          region: null,
          traits: [
            "결혼 후에도 손잡고 다니는 부부를 꿈으로 언급",
            "체력·경제적으로 강인한 여성을 선호 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개' (상철 소개)",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
          {
            title: "블로그: 나는solo 27기 남자 상철 88년생 한전 직원",
            url: "https://blog.naver.com/chummilmil99/223928528212",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "영숙",
        photo: { src: null, alt: "나는 SOLO 27기 영숙" },
        instagram: null,
        profile: {
          birthYear: 1989,
          ageKorean: null,
          job: "외국계 의료기기회사 마케팅 담당자",
          region: null,
          traits: [
            "호주 국적·UNSW 출신, 한국 거주",
            "독서·등산 등 다양한 취미 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(영숙 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "정숙",
        photo: { src: null, alt: "나는 SOLO 27기 정숙" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "포항 소재 이차전지 관련 회사 직원",
          region: "포항",
          traits: [
            "정유미 닮은꼴로 언급",
            "결혼 의지 강하며, 장거리·이직 문제에 민감",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(정숙 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "순자",
        photo: { src: null, alt: "나는 SOLO 27기 순자" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "장애인 B2G 담당자(장애인 대상 기업 연계)",
          region: "대구 출신, 서울 거주",
          traits: [
            "난소 나이 24세라 언급하며 노산 걱정 없음을 강조",
            "결혼 의지 강하고, 계획·계획형 성격 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(순자 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "영자",
        photo: { src: null, alt: "나는 SOLO 27기 영자" },
        instagram: null,
        profile: {
          birthYear: 1992,
          ageKorean: null,
          job: "한국국제협력단(KOICA) 근무",
          region: "경기도 성남 거주",
          traits: [
            "영미권 유학 경험(미국·일본·홍콩) 언급",
            "2년 정도 해외 파견 가능성 언급",
            "사내 밴드·댄스·뜨개질 등 다양한 취미",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(영자 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "옥순",
        photo: { src: null, alt: "나는 SOLO 27기 옥순" },
        instagram: null,
        profile: {
          birthYear: 1991,
          ageKorean: null,
          job: "10년차 패션 디자이너(미국 회사 리모트 근무 형태)",
          region: "서울 용산구 거주 언급",
          traits: [
            "미국 회사 리모트 근무로 상대 편의에 맞출 수 있다는 점 언급",
            "7번 지원한 ‘진짜 옥순’으로 언급",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(옥순 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
      {
        seasonNo: 27,
        gender: "F",
        handle: "현숙",
        photo: { src: null, alt: "나는 SOLO 27기 현숙" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "외국계 제약회사 세일즈",
          region: null,
          traits: [
            "소개팅 100번 이상 경험 언급",
            "귀국·결혼·경제적 자립에 대한 강한 의지 언급",
            "2억 원대 자산 보유·헬스·자기관리 언급(비공식 블로그·기사 기반)",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "bnt 뉴스: '나는솔로 27기 자기소개(현숙 소개)'",
            url: "https://v.daum.net/v/20250710073741558",
            confidence: "high",
          },
        ],
      },
    ],
  },
  {
    seasonNo: 26,
    label: "26기 골드 특집",
    episodes: [
      { ep: 199, airDate: "2025-04-30" },
      { ep: 200, airDate: "2025-05-07" },
      { ep: 201, airDate: "2025-05-14" },
      { ep: 202, airDate: "2025-05-21" },
      { ep: 203, airDate: "2025-05-28" },
      { ep: 204, airDate: "2025-06-04" },
      { ep: 205, airDate: "2025-06-11" },
      { ep: 206, airDate: "2025-06-18" },
      { ep: 207, airDate: "2025-06-25" },
    ],
    participants: [
      {
        seasonNo: 26,
        gender: "M",
        handle: "영수",
        photo: { src: null, alt: "나는 SOLO 26기 영수" },
        instagram: null,
        profile: {
          birthYear: 1981,
          ageKorean: null,
          job: "부산대 공학과 대학교수",
          region: null,
          traits: ["부모님의 반대로 과거 연애 결혼 무산 경험"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "영호",
        photo: { src: null, alt: "나는 SOLO 26기 영호" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "인천시청 소속 공무원",
          region: null,
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "영식",
        photo: { src: null, alt: "나는 SOLO 26기 영식" },
        instagram: null,
        profile: {
          birthYear: 1985,
          ageKorean: null,
          job: "게임 기획자",
          region: null,
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "영철",
        photo: { src: null, alt: "나는 SOLO 26기 영철" },
        instagram: null,
        profile: {
          birthYear: 1985,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["소맥 애호가"],
          notableQuotes: [],
          issues: ["직업 자동 수집 오류(4명 중복) - 수동 입력 필요"],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "광수",
        photo: { src: null, alt: "나는 SOLO 26기 광수" },
        instagram: null,
        profile: {
          birthYear: 1983,
          ageKorean: null,
          job: null,
          region: null,
          traits: [
            "등장부터 빨간 코트+족자 퍼포먼스",
            "모창·개그 가능",
            "어머니와 아직도 뽀뽀한다고 함",
          ],
          notableQuotes: [],
          issues: ["직업 자동 수집 오류(4명 중복) - 수동 입력 필요"],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "상철",
        photo: { src: null, alt: "나는 SOLO 26기 상철" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: null,
          region: null,
          traits: ["봉사활동이 취미", "결이 맞는 사람이 좋다고 언급"],
          notableQuotes: [],
          issues: ["직업 자동 수집 오류(4명 중복) - 수동 입력 필요"],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 프로필 정리",
            url: "https://blog.naver.com/tastyghost/223859146168",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "M",
        handle: "경수",
        photo: { src: null, alt: "나는 SOLO 26기 경수" },
        instagram: null,
        profile: {
          birthYear: 1980,
          ageKorean: null,
          job: null,
          region: null,
          traits: [],
          notableQuotes: [],
          issues: ["직업 자동 수집 오류(4명 중복) - 수동 입력 필요"],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "영숙",
        photo: { src: null, alt: "나는 SOLO 26기 영숙" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "서울 소재 대학교 국제대학 초빙교수",
          region: "부산 출신",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "정숙",
        photo: { src: null, alt: "나는 SOLO 26기 정숙" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "변호사",
          region: null,
          traits: ["피지컬 중시", "결혼은 행복의 전제조건이라 생각"],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "순자",
        photo: { src: null, alt: "나는 SOLO 26기 순자" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "공연 기획자",
          region: null,
          traits: [
            "소개팅에서 눈 마주치기 어려워 0표 예상했다고 밝힘",
            "어머니 반대로 회사원 남성과 결별",
          ],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "옥순",
        photo: { src: null, alt: "나는 SOLO 26기 옥순" },
        instagram: null,
        profile: {
          birthYear: 1988,
          ageKorean: null,
          job: "프리랜서 미술 강사",
          region: "부산 광안리",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "영자",
        photo: { src: null, alt: "나는 SOLO 26기 영자" },
        instagram: null,
        profile: {
          birthYear: 1986,
          ageKorean: null,
          job: "외국계 자문사 컨설턴트",
          region: null,
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
      {
        seasonNo: 26,
        gender: "F",
        handle: "현숙",
        photo: { src: null, alt: "나는 SOLO 26기 현숙" },
        instagram: null,
        profile: {
          birthYear: 1987,
          ageKorean: null,
          job: "미국 변호사",
          region: "서울",
          traits: [],
          notableQuotes: [],
          issues: [],
        },
        sources: [
          {
            title: "네이버 블로그: 나는 SOLO 26기 출연자 직업 나이",
            url: "https://blog.naver.com/movie6miri/223866338251",
            confidence: "medium",
          },
        ],
      },
    ],
  },
];

/** 가장 최신 기수 (배열 첫 번째 = 최신순 정렬 기준) */
export const LATEST_SEASON = SEASONS_DATA[0];
